### ISSUE TITLE
Synchronized 0 items with Zotero library (including notes and attachments), creating 0 and updating 0 items.

### ISSUE THREAD

**Issue by danieltomasz** [cboulanger/bookends-api#8]
I try to set up it first time using 

```
examples/bookends-zotero-sync users/2475454   --key=xxxx
```

with Zotero 5.0.89 and bookend 13.4.4

I am not getting any error but this info
```
Synchronized 0 items with Zotero library (including notes and attachments), creating 0 and updating 0 items.
```
and nothing appears in the Bookends library. What I am doing wrong?

**Comment by cboulanger** [comment]
Hi! Since you mention the Zotero version - the client has nothing to do with it. Synchronization is with the zotero server - but I assume you know that.
I assume that your personal library on the Zotero server contains references, and the Bookends library is empty. Can you try 

```
examples/bookends-zotero-sync users/2475454   --key=xxxx --target=bookends
```

And report what it says? To be honest, I haven't touched this code for ages, but I can try to help...

**Comment by danieltomasz** [comment]
Thanks for the help! The result was the same :( Finally, I am using RIS export to share selected collections between Zotero and Bookends, and for me, it is enough.
